
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.Symbol;
import analizadores.*;
import com.company.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\004\000\002\003\004\000\002\003\003" +
    "\000\002\003\004\000\002\003\003\000\002\003\004\000" +
    "\002\003\003\000\002\004\010\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\005\000\002\005" +
    "\004\000\002\005\004\000\002\005\004\000\002\005\004" +
    "\000\002\006\005\000\002\006\004\000\002\006\005\000" +
    "\002\006\004\000\002\006\005\000\002\006\004\000\002" +
    "\006\005\000\002\006\004\000\002\010\006\000\002\011" +
    "\004\000\002\011\003\000\002\011\004\000\002\011\003" +
    "\000\002\011\004\000\002\011\003\000\002\011\004\000" +
    "\002\011\003\000\002\011\004\000\002\011\003\000\002" +
    "\011\004\000\002\011\003\000\002\011\004\000\002\011" +
    "\003\000\002\011\004\000\002\011\003\000\002\011\004" +
    "\000\002\011\003\000\002\011\004\000\002\011\003\000" +
    "\002\012\003\000\002\013\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\113\000\004\004\004\001\002\000\010\020\016\021" +
    "\013\027\015\001\002\000\004\002\006\001\002\000\004" +
    "\002\001\001\002\000\012\005\ufffa\020\ufffa\021\ufffa\027" +
    "\ufffa\001\002\000\012\005\111\020\016\021\013\027\015" +
    "\001\002\000\012\005\ufff8\020\ufff8\021\ufff8\027\ufff8\001" +
    "\002\000\012\005\uffff\020\uffff\021\uffff\027\uffff\001\002" +
    "\000\012\005\uffd1\020\uffd1\021\uffd1\027\uffd1\001\002\000" +
    "\012\005\ufffc\020\ufffc\021\ufffc\027\ufffc\001\002\000\006" +
    "\006\060\010\057\001\002\000\004\006\017\001\002\000" +
    "\004\027\020\001\002\000\004\010\021\001\002\000\016" +
    "\004\026\023\025\025\024\026\023\030\030\031\027\001" +
    "\002\000\004\007\056\001\002\000\006\013\033\016\054" +
    "\001\002\000\006\013\033\016\050\001\002\000\004\013" +
    "\033\001\002\000\004\016\045\001\002\000\004\013\033" +
    "\001\002\000\004\016\031\001\002\000\004\030\032\001" +
    "\002\000\004\007\ufff4\001\002\000\012\023\037\025\036" +
    "\026\035\031\040\001\002\000\004\007\uffef\001\002\000" +
    "\006\007\uffed\013\033\001\002\000\006\007\uffe7\013\033" +
    "\001\002\000\006\007\uffe9\013\033\001\002\000\006\007" +
    "\uffeb\013\033\001\002\000\004\007\uffec\001\002\000\004" +
    "\007\uffea\001\002\000\004\007\uffe8\001\002\000\004\007" +
    "\uffee\001\002\000\004\005\046\001\002\000\004\007\ufff3" +
    "\001\002\000\004\007\ufff0\001\002\000\004\025\052\001" +
    "\002\000\004\007\ufff1\001\002\000\004\007\ufff5\001\002" +
    "\000\004\007\ufff2\001\002\000\004\026\055\001\002\000" +
    "\004\007\ufff6\001\002\000\012\005\ufff7\020\ufff7\021\ufff7" +
    "\027\ufff7\001\002\000\026\004\071\005\070\011\066\012" +
    "\073\014\065\015\075\017\072\023\064\027\063\031\074" +
    "\001\002\000\004\023\061\001\002\000\004\007\062\001" +
    "\002\000\012\005\uffd0\020\uffd0\021\uffd0\027\uffd0\001\002" +
    "\000\030\004\071\005\070\007\uffde\011\066\012\073\014" +
    "\065\015\075\017\072\023\064\027\063\031\074\001\002" +
    "\000\030\004\071\005\070\007\uffd6\011\066\012\073\014" +
    "\065\015\075\017\072\023\064\027\063\031\074\001\002" +
    "\000\030\004\071\005\070\007\uffd8\011\066\012\073\014" +
    "\065\015\075\017\072\023\064\027\063\031\074\001\002" +
    "\000\030\004\071\005\070\007\uffe4\011\066\012\073\014" +
    "\065\015\075\017\072\023\064\027\063\031\074\001\002" +
    "\000\004\007\104\001\002\000\030\004\071\005\070\007" +
    "\uffe0\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\030\004\071\005\070\007" +
    "\uffe2\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\030\004\071\005\070\007" +
    "\uffda\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\030\004\071\005\070\007" +
    "\uffdc\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\030\004\071\005\070\007" +
    "\uffd2\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\030\004\071\005\070\007" +
    "\uffd4\011\066\012\073\014\065\015\075\017\072\023\064" +
    "\027\063\031\074\001\002\000\004\007\uffd5\001\002\000" +
    "\004\007\uffd3\001\002\000\004\007\uffdd\001\002\000\004" +
    "\007\uffdb\001\002\000\004\007\uffe3\001\002\000\004\007" +
    "\uffe1\001\002\000\012\005\uffe6\020\uffe6\021\uffe6\027\uffe6" +
    "\001\002\000\004\007\uffe5\001\002\000\004\007\uffd9\001" +
    "\002\000\004\007\uffd7\001\002\000\004\007\uffdf\001\002" +
    "\000\004\002\000\001\002\000\012\005\ufffb\020\ufffb\021" +
    "\ufffb\027\ufffb\001\002\000\012\005\ufff9\020\ufff9\021\ufff9" +
    "\027\ufff9\001\002\000\012\005\ufffe\020\ufffe\021\ufffe\027" +
    "\ufffe\001\002\000\012\005\ufffd\020\ufffd\021\ufffd\027\ufffd" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\113\000\004\002\004\001\001\000\014\003\007\004" +
    "\011\010\013\012\006\013\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\004\113\010" +
    "\114\012\111\013\112\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\021\001\001\000\002\001\001\000\004\006" +
    "\052\001\001\000\004\006\050\001\001\000\004\006\046" +
    "\001\001\000\002\001\001\000\004\006\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\043\001\001\000" +
    "\004\006\042\001\001\000\004\006\041\001\001\000\004" +
    "\006\040\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\066\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\107\001\001\000\004\011\106\001\001\000" +
    "\004\011\105\001\001\000\004\011\104\001\001\000\002" +
    "\001\001\000\004\011\102\001\001\000\004\011\101\001" +
    "\001\000\004\011\100\001\001\000\004\011\077\001\001" +
    "\000\004\011\076\001\001\000\004\011\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}






    // error sintactico
    public void syntax_error(Symbol s)
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! XDDDDD Recuperado !!!!!!!");


    }

    //momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! AAAAAAAAAAAAAAAAA, Panic Mode !!!!!!! ");

    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= llavea INICIO2 llavec 
            {
              Object RESULT =null;
		System.out.println("Fin de analisis de entrada");
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO2 ::= CONJUNTOS 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO2 ::= INICIO2 CONJUNTOS 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO2 ::= INICIO2 EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INICIO2 ::= EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INICIO2 ::= INICIO2 PORCENTAJES 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INICIO2 ::= PORCENTAJES 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INICIO2 ::= INICIO2 ENTRADAS 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INICIO2 ::= ENTRADAS 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("INICIO2",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // CONJUNTOS ::= conj dospuntos id flecha COMBINACIONES puntocoma 
            {
              Object RESULT =null;
		int iddleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String idd = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 System.out.println("");System.out.println(idd+" "+combinacion);
                                                                                   Conjunto conjunto = new Conjunto(idd,(String)combinacion);
                                                                                                   Main.conjuntos.add(conjunto);
                                                                                  
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("CONJUNTOS",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // COMBINACIONES ::= letra guionondulado letra 
            {
              Object RESULT =null;
		int letra1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int letra1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String letra1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int guionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int guionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String guion = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int letra2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int letra2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String letra2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=letra1+guion+letra2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // COMBINACIONES ::= numero guionondulado numero 
            {
              Object RESULT =null;
		int numero1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int numero1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String numero1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int guionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int guionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String guion = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int numero2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int numero2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String numero2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=numero1+guion+numero2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // COMBINACIONES ::= simbolos guionondulado simbolos 
            {
              Object RESULT =null;
		int simbolo1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int simbolo1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String simbolo1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int guionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int guionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String guion = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int simbolo2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int simbolo2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String simbolo2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=simbolo1+guion+simbolo2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // COMBINACIONES ::= llavea guionondulado llavec 
            {
              Object RESULT =null;
		int llave1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int llave1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String llave1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int guionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int guionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String guion = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int llave2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int llave2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String llave2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=llave1+guion+llave2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // COMBINACIONES ::= letra COMASLETRA 
            {
              Object RESULT =null;
		int letracoma1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int letracoma1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String letracoma1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int letracoma2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int letracoma2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object letracoma2 = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=letracoma1+letracoma2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // COMBINACIONES ::= numero COMASLETRA 
            {
              Object RESULT =null;
		int numerocoma1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int numerocoma1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String numerocoma1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int numerocoma2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int numerocoma2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object numerocoma2 = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=numerocoma1+numerocoma2; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // COMBINACIONES ::= cadena COMASLETRA 
            {
              Object RESULT =null;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=cadenaa+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // COMBINACIONES ::= caracterEspecial COMASLETRA 
            {
              Object RESULT =null;
		int especialleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int especialright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String especial = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=especial+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONES",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // COMASLETRA ::= coma letra COMASLETRA 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int letracomaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int letracomaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String letracoma = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+letracoma+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // COMASLETRA ::= coma letra 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int letracomaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int letracomaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String letracoma = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+letracoma; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // COMASLETRA ::= coma caracterEspecial COMASLETRA 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int especialleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int especialright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String especial = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+especial+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // COMASLETRA ::= coma caracterEspecial 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int especialleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int especialright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String especial = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+especial; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // COMASLETRA ::= coma cadena COMASLETRA 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+cadenaa+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // COMASLETRA ::= coma cadena 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+cadenaa; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // COMASLETRA ::= coma numero COMASLETRA 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int numerocomaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int numerocomaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String numerocoma = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+numerocoma+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // COMASLETRA ::= coma numero 
            {
              Object RESULT =null;
		int comaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int comaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String comaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int numerocomaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int numerocomaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String numerocoma = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=comaa+numerocoma; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMASLETRA",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESIONES ::= id flecha COMBINACIONESEXPRESIONES puntocoma 
            {
              Object RESULT =null;
		int iddleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String idd = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int expresionnleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int expresionnright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object expresionn = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 System.out.println("");System.out.println(idd+expresionn);
                                                                                       Expresion expresion = new Expresion(idd,(String)expresionn);
                                                                                                       Main.expresiones.add(expresion);
                                                                                      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // COMBINACIONESEXPRESIONES ::= punto COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int puntooleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int puntooright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String puntoo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=puntoo+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // COMBINACIONESEXPRESIONES ::= punto 
            {
              Object RESULT =null;
		int puntooleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int puntooright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String puntoo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=puntoo; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // COMBINACIONESEXPRESIONES ::= llavea COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int llaveaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int llaveaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String llaveaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=llaveaa+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // COMBINACIONESEXPRESIONES ::= llavea 
            {
              Object RESULT =null;
		int llaveaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int llaveaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String llaveaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=llaveaa; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // COMBINACIONESEXPRESIONES ::= llavec COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int llaveccleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int llaveccright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String llavecc = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=llavecc+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // COMBINACIONESEXPRESIONES ::= llavec 
            {
              Object RESULT =null;
		int llaveccleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int llaveccright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String llavecc = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=llavecc; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // COMBINACIONESEXPRESIONES ::= id COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int iddleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String idd = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=idd+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // COMBINACIONESEXPRESIONES ::= id 
            {
              Object RESULT =null;
		int iddleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String idd = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=idd; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // COMBINACIONESEXPRESIONES ::= asterisco COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int asteriscooleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int asteriscooright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String asteriscoo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=asteriscoo+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // COMBINACIONESEXPRESIONES ::= asterisco 
            {
              Object RESULT =null;
		int asteriscooleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int asteriscooright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String asteriscoo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=asteriscoo; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // COMBINACIONESEXPRESIONES ::= interrogacion COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int interrogacionnleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int interrogacionnright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String interrogacionn = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=interrogacionn+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // COMBINACIONESEXPRESIONES ::= interrogacion 
            {
              Object RESULT =null;
		int interrogacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int interrogacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String interrogacion = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=interrogacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // COMBINACIONESEXPRESIONES ::= or COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int orrleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int orrright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String orr = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=orr+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // COMBINACIONESEXPRESIONES ::= or 
            {
              Object RESULT =null;
		int orrleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int orrright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String orr = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=orr; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // COMBINACIONESEXPRESIONES ::= cadena COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=cadenaa+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // COMBINACIONESEXPRESIONES ::= cadena 
            {
              Object RESULT =null;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=cadenaa; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // COMBINACIONESEXPRESIONES ::= mas COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int massleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int massright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String mass = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=mass+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // COMBINACIONESEXPRESIONES ::= mas 
            {
              Object RESULT =null;
		int massleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int massright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String mass = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT=mass;  
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // COMBINACIONESEXPRESIONES ::= caracterEspecial COMBINACIONESEXPRESIONES 
            {
              Object RESULT =null;
		int especialleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int especialright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String especial = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int combinacionleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int combinacionright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object combinacion = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 String especial2 = "\""+"\\"+"\"";
                                                                    RESULT=especial2+combinacion; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // COMBINACIONESEXPRESIONES ::= caracterEspecial 
            {
              Object RESULT =null;
		int especialleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int especialright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String especial = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		  String especial2 = "\""+"\\"+"\"";
                                RESULT=especial2;  
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("COMBINACIONESEXPRESIONES",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // PORCENTAJES ::= porcentajes 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("PORCENTAJES",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ENTRADAS ::= id dospuntos cadena puntocoma 
            {
              Object RESULT =null;
		int iddleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String idd = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int cadenaaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cadenaaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String cadenaa = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 System.out.println("");System.out.println(idd+cadenaa);
                                                                       Expresion expresion2 = new Expresion(idd,cadenaa);
                                                                                       Main.entradas.add(expresion2);
                                                                      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("ENTRADAS",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
